title: DIY slow lamp
description: tutorial
theme: just-the-docs

url: https://gocivici.github.io/DIYslowlamp

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
